# help.eworldq8.com :: guides
#
# The substance of the site. Each guide is something a person can follow on
# their own, written in the order they should actually do things, and every
# one ends with when to stop and ask, because the wrong step at the wrong
# moment (recovery software onto a failing drive, a hairdryer on a wet
# laptop) does more harm than the original problem.
#
# Every string carries both languages. The Arabic is written as Arabic, with
# clauses joined rather than chopped, and uses Western digits.

CATEGORIES = [
    {"key": "computers", "name": {"en": "Laptops and desktops", "ar": "الحواسيب المحمولة والمكتبية"}},
    {"key": "phones",    "name": {"en": "Phones and tablets",   "ar": "الهواتف والأجهزة اللوحية"}},
    {"key": "websites",  "name": {"en": "Websites",             "ar": "المواقع الإلكترونية"}},
    {"key": "files",     "name": {"en": "Files and backups",    "ar": "الملفات والنسخ الاحتياطي"}},
    {"key": "network",   "name": {"en": "Wi-Fi and networks",   "ar": "الواي فاي والشبكات"}},
    {"key": "safety",    "name": {"en": "Staying safe online",  "ar": "الأمان على الإنترنت"}},
]

GUIDES = [
{
 "slug": "laptop-will-not-turn-on", "category": "computers", "urgency": "normal",
 "title": {"en": "My laptop will not turn on", "ar": "حاسوبي المحمول لا يشتغل"},
 "summary": {"en": "What to check, in the order that rules things out fastest, before you assume the worst.",
             "ar": "ما ينبغي فحصه بالترتيب الذي يستبعد الاحتمالات أسرع، قبل أن تفترض الأسوأ."},
 "keywords": {"en": "dead laptop power button no lights charger battery", "ar": "لابتوب لا يعمل زر التشغيل لا يضيء شاحن بطارية"},
 "steps": [
  {"en": "Look at the charger. Is there a light on the brick or on the laptop where it plugs in? No light at all usually means the charger or the socket, not the laptop.",
   "ar": "انظر إلى الشاحن، هل يضيء مؤشر على المحوّل أو على الحاسوب عند مدخل الشحن؟ فغياب أيّ ضوء يعني غالباً الشاحن أو المقبس لا الحاسوب."},
  {"en": "Try a different wall socket, and a different cable if the charger has a detachable one.",
   "ar": "جرّب مقبساً آخر في الحائط، وكابلاً آخر إن كان الشاحن يقبل كابلاً منفصلاً."},
  {"en": "Unplug the charger, then hold the power button down for a full thirty seconds. This drains the board. Plug the charger back in and press power once.",
   "ar": "افصل الشاحن ثم اضغط زر التشغيل ثلاثين ثانية كاملة، فهذا يفرّغ اللوحة من الشحنة، ثم أعد الشاحن واضغط زر التشغيل مرة واحدة."},
  {"en": "Listen and feel. A fan spinning or a faint click means the board is getting power and the problem is further along, often the screen.",
   "ar": "أنصت وتحسّس، فدوران مروحة أو طقطقة خافتة يعني أنّ اللوحة تصلها الطاقة وأنّ المشكلة أبعد من ذلك، وغالباً في الشاشة."},
  {"en": "If there is a fan or a click but no picture, plug it into a TV or an external monitor. If that shows a picture, the laptop is fine and the screen is not.",
   "ar": "فإن كانت هناك مروحة أو طقطقة بلا صورة فوصّله بتلفاز أو بشاشة خارجية، فإن ظهرت الصورة هناك فالحاسوب سليم والشاشة ليست كذلك."},
 ],
 "stop": {"en": "If nothing at all happens with a known good charger and socket, or if the machine has ever been dropped or had liquid near it, stop here and ask. Opening it up without knowing what failed usually makes a cheap repair expensive.",
          "ar": "فإن لم يحدث شيء إطلاقاً مع شاحن ومقبس سليمين، أو إن سقط الجهاز يوماً أو اقترب منه سائل، فتوقّف هنا واسألنا، لأنّ فتحه دون معرفة العطل يجعل الإصلاح الرخيص مكلفاً."},
},
{
 "slug": "computer-is-very-slow", "category": "computers", "urgency": "low",
 "title": {"en": "My computer has become very slow", "ar": "حاسوبي صار بطيئاً جداً"},
 "summary": {"en": "Three causes account for almost every slow machine, and you can check all three in ten minutes.",
             "ar": "ثلاثة أسباب تفسّر أغلب الأجهزة البطيئة، ويمكنك فحصها كلّها في عشر دقائق."},
 "keywords": {"en": "slow lag freezing disk full startup programs", "ar": "بطيء تجمّد قرص ممتلئ برامج بدء التشغيل"},
 "steps": [
  {"en": "Restart it properly, not sleep, not close the lid. A machine that has been on for weeks slows down on its own and a restart costs nothing.",
   "ar": "أعد تشغيله فعلاً، لا وضع السكون ولا إغلاق الغطاء، فجهاز بقي يعمل أسابيع يبطؤ من تلقاء نفسه وإعادة التشغيل لا تكلّف شيئاً."},
  {"en": "Check free space on the main drive. On Windows open This PC, on a Mac open About This Mac then Storage. Under ten per cent free will slow any machine down.",
   "ar": "انظر إلى المساحة الفارغة في القرص الأساسي، ففي ويندوز افتح هذا الكمبيوتر وفي ماك افتح حول هذا الماك ثم التخزين، وأقلّ من عشرة بالمئة يُبطئ أيّ جهاز."},
  {"en": "If space is the problem, the Downloads folder and the Recycle Bin are the usual culprits. Empty the bin, then sort Downloads by size.",
   "ar": "فإن كانت المساحة هي المشكلة فمجلد التنزيلات وسلّة المحذوفات هما المتّهمان المعتادان، فأفرغ السلّة ثم رتّب التنزيلات بحسب الحجم."},
  {"en": "Look at what starts with the machine. On Windows press Ctrl, Shift and Esc together, then the Startup tab. On a Mac it is System Settings, General, Login Items. Turn off anything you do not recognise as essential.",
   "ar": "انظر إلى ما يبدأ مع الجهاز، ففي ويندوز اضغط Ctrl وShift وEsc معاً ثم تبويب بدء التشغيل، وفي ماك إعدادات النظام ثم عام ثم عناصر تسجيل الدخول، وأوقف كلّ ما لا تعرفه أساسياً."},
  {"en": "If the machine is more than five years old and still on a mechanical hard drive, nothing above will fix it for long. A solid state drive is the single most effective upgrade there is.",
   "ar": "وإن كان الجهاز أقدم من خمس سنوات وما زال على قرص ميكانيكي فلن يدوم أثر شيء ممّا سبق، فالقرص الصلب الإلكتروني هو أنفع ترقية على الإطلاق."},
 ],
 "stop": {"en": "If it is slow and also making clicking or grinding noises, stop using it and copy your important files somewhere else today. That is a drive on its way out.",
          "ar": "فإن كان بطيئاً ويصدر أيضاً أصوات طقطقة أو احتكاك فأوقف استعماله وانسخ ملفاتك المهمّة إلى مكان آخر اليوم، فذلك قرص في طريقه إلى التعطّل."},
},
{
 "slug": "laptop-overheating", "category": "computers", "urgency": "normal",
 "title": {"en": "My laptop gets hot and the fan is loud", "ar": "حاسوبي المحمول يسخن والمروحة عالية الصوت"},
 "summary": {"en": "Why it happens, what helps, and the one popular fix that makes it worse.",
             "ar": "لماذا يحدث ذلك وما الذي يفيد، والحلّ الشائع الوحيد الذي يزيد الأمر سوءاً."},
 "keywords": {"en": "hot overheating fan noise thermal dust shutdown", "ar": "ساخن حرارة مروحة صوت غبار انطفاء"},
 "steps": [
  {"en": "Use it on a hard, flat surface. A bed, a sofa or your lap blocks the vents underneath and the machine cannot cool itself.",
   "ar": "استعمله على سطح صلب مستوٍ، فالسرير أو الأريكة أو حجرك يسدّ الفتحات في الأسفل فلا يستطيع الجهاز أن يبرّد نفسه."},
  {"en": "Check what is working hard. A browser with forty tabs, a video call and a sync program all at once will heat any laptop. Close what you are not using.",
   "ar": "انظر إلى ما يعمل بجهد، فمتصفح فيه أربعون تبويباً ومكالمة فيديو وبرنامج مزامنة معاً يسخّن أيّ حاسوب، فأغلق ما لا تستعمله."},
  {"en": "Look at the vents with a torch. If you can see dust packed in the grille, that is the cause. Dust builds up faster in hot, dusty climates and gets worse every summer.",
   "ar": "انظر إلى الفتحات بمصباح، فإن رأيت غباراً متكدّساً في الشبكة فهذا هو السبب، والغبار يتراكم أسرع في المناخات الحارّة المغبرّة ويزداد كلّ صيف."},
  {"en": "Do not blow compressed air into the vents. It pushes the dust deeper and can spin the fan faster than it is designed for. Cleaning properly means opening it up.",
   "ar": "لا تنفخ الهواء المضغوط في الفتحات، فهو يدفع الغبار أعمق وقد يدير المروحة أسرع ممّا صُمّمت له، والتنظيف الصحيح يعني فتح الجهاز."},
  {"en": "If it is more than three years old, the thermal paste between the chip and the cooler has probably dried out. Replacing it is routine and makes a large difference.",
   "ar": "وإن كان أقدم من ثلاث سنوات فالأرجح أنّ المعجون الحراري بين الشريحة والمبرّد قد جفّ، وتبديله عمل روتيني يُحدث فرقاً كبيراً."},
 ],
 "stop": {"en": "If it shuts itself off while you are working, that is the machine protecting itself from heat damage. Stop using it for anything long until it has been cleaned.",
          "ar": "فإن كان ينطفئ من تلقاء نفسه وأنت تعمل فذلك الجهاز يحمي نفسه من تلف الحرارة، فأوقف استعماله في أيّ عمل طويل حتى يُنظَّف."},
},
{
 "slug": "liquid-spilled-on-laptop", "category": "computers", "urgency": "urgent",
 "title": {"en": "I spilled a drink on my laptop", "ar": "انسكب مشروب على حاسوبي المحمول"},
 "summary": {"en": "The first ten minutes decide whether this is a cleaning or a new laptop. Do these in order, now.",
             "ar": "الدقائق العشر الأولى تقرّر إن كان الأمر تنظيفاً أم حاسوباً جديداً، فافعل هذه بالترتيب الآن."},
 "keywords": {"en": "spill water coffee tea liquid wet keyboard emergency", "ar": "انسكاب ماء قهوة شاي سائل مبلّل لوحة مفاتيح طوارئ"},
 "steps": [
  {"en": "Turn it off now. Hold the power button until everything goes dark. Do not shut down the normal way, do not save your work, do not wait.",
   "ar": "أطفئه الآن، واضغط زر التشغيل حتى يظلم كلّ شيء، ولا تُغلقه بالطريقة المعتادة ولا تحفظ عملك ولا تنتظر."},
  {"en": "Unplug the charger. If the battery comes out without tools, take it out.",
   "ar": "افصل الشاحن، وإن كانت البطارية تخرج دون أدوات فأخرجها."},
  {"en": "Open the lid as far as it goes and turn the whole thing upside down like a tent, on a towel. You want the liquid to drain out through the keyboard, not further in.",
   "ar": "افتح الغطاء إلى أقصاه واقلب الجهاز كلّه كالخيمة على منشفة، فالمطلوب أن يخرج السائل عبر لوحة المفاتيح لا أن يتوغّل أعمق."},
  {"en": "Leave it like that. Do not use rice, which does nothing and leaves starch in the keyboard. Do not use a hairdryer, which drives moisture into the board and can warp plastics.",
   "ar": "اتركه كذلك، ولا تستعمل الأرزّ فهو لا يفعل شيئاً ويترك نشاءً في لوحة المفاتيح، ولا مجفّف الشعر فهو يدفع الرطوبة إلى اللوحة وقد يشوّه البلاستيك."},
  {"en": "Do not turn it on to check, not even for a second. Power on a wet board is what causes the permanent damage. The liquid itself mostly does not.",
   "ar": "لا تشغّله لتتأكّد ولا حتى لثانية، فالتيار على لوحة مبلّلة هو ما يسبّب التلف الدائم، أمّا السائل نفسه فنادراً ما يفعل."},
 ],
 "stop": {"en": "Get in touch the same day. Anything sugary, coffee, juice, a soft drink, leaves a residue that corrodes the board over the following days even after it looks dry. A proper clean within a day or two nearly always saves it.",
          "ar": "تواصل معنا في اليوم نفسه، فكلّ سائل فيه سكّر، من قهوة أو عصير أو مشروب غازي، يترك رواسب تتآكل بها اللوحة في الأيام التالية حتى بعد أن يبدو جافاً، والتنظيف السليم خلال يوم أو يومين ينقذه في الغالب."},
},
{
 "slug": "blue-screen-and-restarts", "category": "computers", "urgency": "normal",
 "title": {"en": "It shows a blue screen or restarts on its own", "ar": "تظهر شاشة زرقاء أو يعيد التشغيل من تلقاء نفسه"},
 "summary": {"en": "The message on the screen is the clue. Here is how to capture it and what the common ones mean.",
             "ar": "الرسالة على الشاشة هي الدليل، وهكذا تلتقطها وهذا ما تعنيه الرسائل الشائعة."},
 "keywords": {"en": "blue screen BSOD crash restart error code stop code", "ar": "شاشة زرقاء تعطّل إعادة تشغيل رمز خطأ"},
 "steps": [
  {"en": "Next time it happens, photograph the screen with your phone before it restarts. The line that says Stop code or the text in capitals is what matters.",
   "ar": "في المرة القادمة صوّر الشاشة بهاتفك قبل أن يعيد التشغيل، فالسطر الذي يقول Stop code أو النصّ بالحروف الكبيرة هو ما يهمّ."},
  {"en": "Think about what changed. A new program, a Windows update, a new printer or webcam, or new memory installed. Crashes that start right after a change are almost always that change.",
   "ar": "فكّر فيما تغيّر، برنامج جديد أو تحديث ويندوز أو طابعة أو كاميرا جديدة أو ذاكرة رُكّبت حديثاً، فالأعطال التي تبدأ بعد تغيير تكون ذلك التغيير في الغالب."},
  {"en": "If it mentions MEMORY, PAGE FAULT or IRQL, that points at the memory or a driver. If it mentions a file ending in .sys, that is a driver, usually for graphics, network or storage.",
   "ar": "فإن ذكرت الرسالة MEMORY أو PAGE FAULT أو IRQL فذلك يشير إلى الذاكرة أو إلى مشغّل، وإن ذكرت ملفاً ينتهي بـ .sys فذلك مشغّل، وغالباً للرسومات أو الشبكة أو التخزين."},
  {"en": "Run the built in memory check. On Windows search for Windows Memory Diagnostic and let it restart and test. It takes a while and tells you plainly if the memory is bad.",
   "ar": "شغّل فحص الذاكرة المدمج، ففي ويندوز ابحث عن Windows Memory Diagnostic ودعه يعيد التشغيل ويفحص، ويستغرق وقتاً لكنه يخبرك بوضوح إن كانت الذاكرة معطوبة."},
  {"en": "If it also runs hot or makes noise, the crashes may be heat or a failing drive rather than software. Those two guides cover it.",
   "ar": "وإن كان يسخن أيضاً أو يصدر صوتاً فقد تكون الأعطال من الحرارة أو من قرص يتعطّل لا من البرمجيات، وذلك ما يغطّيه الدليلان الآخران."},
 ],
 "stop": {"en": "If it crashes before Windows even finishes loading, or the same crash comes back after the memory test passes, send us the photo of the screen. That message usually tells us exactly what to replace.",
          "ar": "فإن كان يتعطّل قبل أن يكتمل تحميل ويندوز، أو عاد العطل نفسه بعد أن نجح فحص الذاكرة، فأرسل لنا صورة الشاشة، فتلك الرسالة تخبرنا غالباً بما ينبغي تبديله بالضبط."},
},
{
 "slug": "recover-deleted-files", "category": "files", "urgency": "urgent",
 "title": {"en": "I deleted files I need back", "ar": "حذفت ملفات أحتاجها"},
 "summary": {"en": "Most deleted files can come back. Whether they do depends on what you do in the next hour.",
             "ar": "أغلب الملفات المحذوفة يمكن استرجاعها، وذلك يتوقّف على ما تفعله في الساعة القادمة."},
 "keywords": {"en": "deleted recover restore lost files recycle bin trash undelete", "ar": "حذف استرجاع ملفات مفقودة سلّة المحذوفات"},
 "steps": [
  {"en": "Check the Recycle Bin or Trash first. Deleted files sit there until it is emptied, and restoring from there is a right click.",
   "ar": "انظر أولاً في سلّة المحذوفات، فالملفات المحذوفة تبقى فيها حتى تُفرَّغ، واستعادتها من هناك نقرة يمين."},
  {"en": "If it was a cloud folder, OneDrive, Google Drive, iCloud or Dropbox, open the service in a browser and look for its own bin. They keep deleted files for thirty days.",
   "ar": "وإن كان مجلداً سحابياً، من OneDrive أو Google Drive أو iCloud أو Dropbox، فافتح الخدمة في المتصفح وابحث عن سلّتها الخاصة، فهي تحتفظ بالمحذوفات ثلاثين يوماً."},
  {"en": "If it is gone from both, stop using that drive now. Every file you save, every update that installs, can write over the space your file was in.",
   "ar": "فإن كان قد ذهب من الاثنتين فأوقف استعمال ذلك القرص الآن، فكلّ ملف تحفظه وكلّ تحديث يُثبَّت قد يكتب فوق المساحة التي كان فيها ملفك."},
  {"en": "Do not install recovery software onto the same drive the files were on. Installing it there is one of the things that overwrites them.",
   "ar": "لا تُثبّت برامج الاسترجاع على القرص نفسه الذي كانت فيه الملفات، فتثبيتها هناك من الأمور التي تكتب فوقها."},
  {"en": "If you have a backup, Windows File History, Time Machine, or a cloud backup, restore from that instead. It is quicker and certain.",
   "ar": "وإن كانت لديك نسخة احتياطية، من File History في ويندوز أو Time Machine أو نسخة سحابية، فاسترجع منها بدلاً من ذلك، فهي أسرع وأضمن."},
 ],
 "stop": {"en": "For anything that really matters, photographs, work you cannot redo, get in touch before trying recovery tools yourself. The first recovery attempt is the one most likely to succeed, and a failed one can make the next one impossible.",
          "ar": "ولكلّ ما يهمّ فعلاً، من صور أو عمل لا تستطيع إعادته، تواصل معنا قبل أن تجرّب أدوات الاسترجاع بنفسك، فالمحاولة الأولى هي الأرجح نجاحاً، والمحاولة الفاشلة قد تجعل التالية مستحيلة."},
},
{
 "slug": "set-up-a-backup", "category": "files", "urgency": "low",
 "title": {"en": "Set up a backup that actually runs", "ar": "إعداد نسخ احتياطي يعمل فعلاً"},
 "summary": {"en": "A backup you have to remember is not a backup. Here is the twenty minute setup that runs itself.",
             "ar": "النسخة التي عليك أن تتذكّرها ليست نسخة احتياطية، وهذا إعداد في عشرين دقيقة يعمل من تلقاء نفسه."},
 "keywords": {"en": "backup automatic external drive cloud time machine file history", "ar": "نسخ احتياطي تلقائي قرص خارجي سحابة"},
 "steps": [
  {"en": "Decide what matters. For most people it is Documents, Pictures and the Desktop. Programs can be reinstalled; your photos cannot.",
   "ar": "حدّد ما يهمّ، وهو عند أغلب الناس المستندات والصور وسطح المكتب، فالبرامج يمكن إعادة تثبيتها أمّا صورك فلا."},
  {"en": "Get an external drive at least twice the size of what you are backing up. It does not need to be fast or fancy, it needs to be plugged in.",
   "ar": "احصل على قرص خارجي بضعف حجم ما تنسخه على الأقلّ، ولا يلزم أن يكون سريعاً ولا فاخراً بل أن يكون موصولاً."},
  {"en": "On Windows, search for File History, choose the drive, and turn it on. On a Mac, plug the drive in and say yes when it offers to use it for Time Machine. Both then run on their own.",
   "ar": "في ويندوز ابحث عن File History واختر القرص وشغّله، وفي ماك وصّل القرص ووافق حين يعرض استعماله لـ Time Machine، وكلاهما يعمل بعد ذلك من تلقاء نفسه."},
  {"en": "Add a second copy somewhere else. A drive next to the computer is lost in the same theft, flood or fire. OneDrive, iCloud or Google Drive syncing your Documents and Pictures covers that.",
   "ar": "أضف نسخة ثانية في مكان آخر، فالقرص المجاور للحاسوب يضيع في السرقة أو الفيضان أو الحريق نفسه، ومزامنة المستندات والصور عبر OneDrive أو iCloud أو Google Drive تغطّي ذلك."},
  {"en": "Test it once. Pick a file, delete it, restore it from the backup. If you cannot do that in five minutes, the backup is not set up yet.",
   "ar": "جرّبه مرة واحدة، فاختر ملفاً واحذفه ثم استرجعه من النسخة، فإن لم تستطع ذلك في خمس دقائق فالنسخ الاحتياطي لم يُعدّ بعد."},
 ],
 "stop": {"en": "If you run a business and the files are customer or financial records, the setup above is the floor, not the ceiling. Ask us about something with versions and a tested restore.",
          "ar": "وإن كنت تدير عملاً وكانت الملفات سجلّات عملاء أو سجلّات مالية فالإعداد أعلاه هو الحدّ الأدنى لا الأقصى، فاسألنا عن حلّ بإصدارات واسترجاع مجرَّب."},
},
{
 "slug": "wifi-keeps-dropping", "category": "network", "urgency": "low",
 "title": {"en": "My Wi-Fi keeps dropping", "ar": "الواي فاي ينقطع باستمرار"},
 "summary": {"en": "First find out whether it is the router or the device, because the fix is completely different.",
             "ar": "اعرف أولاً هل المشكلة في الراوتر أم في الجهاز، لأنّ الحلّ مختلف تماماً."},
 "keywords": {"en": "wifi wireless dropping disconnect router slow internet signal", "ar": "واي فاي انقطاع راوتر إنترنت بطيء إشارة"},
 "steps": [
  {"en": "Check another device. If your phone also drops on the same Wi-Fi, it is the router or the connection, not your laptop.",
   "ar": "جرّب جهازاً آخر، فإن كان هاتفك ينقطع أيضاً على الواي فاي نفسه فالمشكلة في الراوتر أو في الاتصال لا في حاسوبك."},
  {"en": "Restart the router properly. Unplug it from the wall, wait a full minute, plug it back in and give it three minutes to come up. Most drops stop here.",
   "ar": "أعد تشغيل الراوتر كما ينبغي، فافصله من الحائط وانتظر دقيقة كاملة ثم أعده وامنحه ثلاث دقائق ليعمل، وأغلب الانقطاعات تتوقّف هنا."},
  {"en": "Look at where the router is. Inside a cabinet, behind a TV or in a far corner cuts the signal badly. Higher and more central is better, and away from the microwave.",
   "ar": "انظر إلى مكان الراوتر، فداخل خزانة أو خلف تلفاز أو في زاوية بعيدة يضعف الإشارة كثيراً، والأعلى والأقرب إلى المنتصف أفضل، وبعيداً عن الميكروويف."},
  {"en": "If only one device drops, tell that device to forget the network and join it again with the password. This clears a stale connection profile.",
   "ar": "وإن كان جهاز واحد فقط ينقطع فاجعله ينسى الشبكة ثم انضمّ إليها من جديد بكلمة المرور، فهذا يمسح ملف اتصال قديم."},
  {"en": "If the router is more than five years old and drops even after all this, it is at the end of its life. Replacing it fixes more than any setting will.",
   "ar": "وإن كان الراوتر أقدم من خمس سنوات وما زال ينقطع بعد كلّ هذا فقد بلغ نهاية عمره، وتبديله يصلح أكثر ممّا يصلحه أيّ إعداد."},
 ],
 "stop": {"en": "If the drops happen on every device and a router restart does not help for more than a day, the fault is usually on the provider's side. Ask them to check the line before buying anything.",
          "ar": "فإن كانت الانقطاعات في كلّ الأجهزة ولم تفد إعادة تشغيل الراوتر أكثر من يوم فالعطل غالباً عند مزوّد الخدمة، فاطلب منهم فحص الخطّ قبل أن تشتري شيئاً."},
},
{
 "slug": "phone-storage-full", "category": "phones", "urgency": "low",
 "title": {"en": "My phone says storage is full", "ar": "هاتفي يقول إنّ التخزين ممتلئ"},
 "summary": {"en": "It is almost always photos and video, and you can free most of it without deleting anything you want.",
             "ar": "هي الصور والفيديو في الغالب الأعمّ، ويمكنك تحرير أغلب المساحة دون أن تحذف شيئاً تريده."},
 "keywords": {"en": "storage full space photos videos iphone android cleanup", "ar": "تخزين ممتلئ مساحة صور فيديو آيفون أندرويد"},
 "steps": [
  {"en": "Look at the breakdown before deleting anything. On iPhone it is Settings, General, iPhone Storage. On Android it is Settings, Storage. It shows exactly what is taking the space.",
   "ar": "انظر إلى التفصيل قبل أن تحذف شيئاً، ففي آيفون الإعدادات ثم عام ثم تخزين iPhone، وفي أندرويد الإعدادات ثم التخزين، وهو يعرض بالضبط ما يشغل المساحة."},
  {"en": "Videos are the big one. A single minute of high quality video is bigger than a hundred photos. Sort the camera roll by videos first.",
   "ar": "الفيديو هو الأكبر، فدقيقة واحدة بجودة عالية أكبر من مئة صورة، فرتّب ألبوم الكاميرا بالفيديو أولاً."},
  {"en": "Turn on cloud photos with optimise storage. iCloud Photos on iPhone, Google Photos on Android. Full quality goes to the cloud and the phone keeps a small copy. This alone usually frees the most space.",
   "ar": "شغّل الصور السحابية مع خيار تحسين التخزين، iCloud Photos في آيفون وGoogle Photos في أندرويد، فتذهب الجودة الكاملة إلى السحابة ويحتفظ الهاتف بنسخة صغيرة، وهذا وحده يحرّر أكبر مساحة عادةً."},
  {"en": "Check WhatsApp. Its media folder is often several gigabytes of forwarded videos. In WhatsApp, Settings, Storage and Data, Manage Storage shows the largest ones.",
   "ar": "افحص واتساب، فمجلد وسائطه يبلغ غالباً عدّة جيجابايت من الفيديوهات المُعاد توجيهها، وفي واتساب الإعدادات ثم التخزين والبيانات ثم إدارة التخزين تجد الأكبر منها."},
  {"en": "Offload apps you have not opened in months. On iPhone that option is under each app in iPhone Storage and keeps your data. On Android just uninstall and reinstall later if needed.",
   "ar": "أزل التطبيقات التي لم تفتحها منذ شهور، ففي آيفون الخيار تحت كلّ تطبيق في تخزين iPhone ويحتفظ ببياناتك، وفي أندرويد ألغِ التثبيت وأعده لاحقاً عند الحاجة."},
 ],
 "stop": {"en": "If the storage screen shows a large System or Other section that will not shrink, that is usually cache the phone should clear itself. A restart, then leaving it plugged in overnight, often does it. If not, ask.",
          "ar": "فإن عرضت شاشة التخزين قسماً كبيراً باسم النظام أو أخرى لا ينكمش فذلك غالباً ذاكرة مؤقّتة ينبغي أن يمسحها الهاتف بنفسه، وإعادة التشغيل ثم تركه موصولاً بالشاحن ليلة كاملة يحلّ ذلك غالباً، وإلا فاسألنا."},
},
{
 "slug": "phone-battery-draining", "category": "phones", "urgency": "low",
 "title": {"en": "My phone battery drains too fast", "ar": "بطارية هاتفي تنفد بسرعة"},
 "summary": {"en": "How to tell a worn battery from an app that is eating it, and what to do about each.",
             "ar": "كيف تفرّق بين بطارية استُهلكت وتطبيق يلتهمها، وما تفعل في كلّ حالة."},
 "keywords": {"en": "battery drain fast health percentage charging replace", "ar": "بطارية تنفد بسرعة صحة البطارية شحن تبديل"},
 "steps": [
  {"en": "Check battery health first. On iPhone it is Settings, Battery, Battery Health. Below eighty per cent, the battery is simply worn out and nothing in software will fix it.",
   "ar": "افحص صحة البطارية أولاً، ففي آيفون الإعدادات ثم البطارية ثم صحة البطارية، وما دون ثمانين بالمئة يعني أنّ البطارية استُهلكت ولن يصلحها شيء في البرمجيات."},
  {"en": "If health is fine, look at the battery usage list on the same screen. One app near the top using far more than the others is your answer.",
   "ar": "وإن كانت الصحة جيّدة فانظر إلى قائمة استهلاك البطارية في الشاشة نفسها، فتطبيق واحد في الأعلى يستهلك أكثر من غيره بكثير هو الجواب."},
  {"en": "Turn off background refresh for apps that do not need it. Social media, shopping and news apps all poll constantly. Settings, General, Background App Refresh on iPhone.",
   "ar": "أوقف التحديث في الخلفية للتطبيقات التي لا تحتاجه، فتطبيقات التواصل والتسوّق والأخبار كلّها تستطلع باستمرار، وفي آيفون الإعدادات ثم عام ثم تحديث التطبيقات في الخلفية."},
  {"en": "Check screen brightness and how long the screen stays on. These two use more power than anything else on the phone.",
   "ar": "افحص سطوع الشاشة ومدّة بقائها مضاءة، فهذان يستهلكان طاقة أكثر من أيّ شيء آخر في الهاتف."},
  {"en": "Weak signal drains a battery fast because the phone keeps searching. If it is worst in one building, that is why, and there is not much to do except Wi-Fi calling.",
   "ar": "الإشارة الضعيفة تستنزف البطارية بسرعة لأنّ الهاتف يظلّ يبحث، فإن كان الأمر أسوأ في مبنى بعينه فهذا هو السبب، وليس هناك كثير يُفعل سوى الاتصال عبر الواي فاي."},
 ],
 "stop": {"en": "A battery replacement is a routine job and usually the right call on any phone over two years old. If the phone gets hot while charging or the back is starting to bulge, stop charging it and get in touch today.",
          "ar": "تبديل البطارية عمل روتيني وهو الخيار الصحيح غالباً لأيّ هاتف عمره أكثر من سنتين، وإن كان الهاتف يسخن أثناء الشحن أو بدأ ظهره ينتفخ فأوقف شحنه وتواصل معنا اليوم."},
},
{
 "slug": "website-is-down", "category": "websites", "urgency": "urgent",
 "title": {"en": "My website will not load", "ar": "موقعي لا يفتح"},
 "summary": {"en": "Three things expire and take a site down with them. Check them in this order.",
             "ar": "ثلاثة أشياء تنتهي صلاحيتها وتُسقط الموقع معها، فافحصها بهذا الترتيب."},
 "keywords": {"en": "website down not loading domain expired hosting dns error", "ar": "موقع لا يفتح متوقّف نطاق منتهٍ استضافة"},
 "steps": [
  {"en": "Open it on your phone using mobile data, not Wi-Fi. If it loads there, the site is fine and the problem is your own network.",
   "ar": "افتحه على هاتفك ببيانات الجوّال لا بالواي فاي، فإن فتح هناك فالموقع سليم والمشكلة في شبكتك أنت."},
  {"en": "Read the error. A browser page saying the site cannot be found means the domain. A page from your hosting company means hosting. A blank page or a database error means the site itself.",
   "ar": "اقرأ الخطأ، فصفحة من المتصفح تقول إنّ الموقع غير موجود تعني النطاق، وصفحة من شركة الاستضافة تعني الاستضافة، وصفحة فارغة أو خطأ في قاعدة البيانات يعني الموقع نفسه."},
  {"en": "Search your email for renewal, expired and the name of your domain. An expired domain is the most common cause and takes minutes to fix if you catch it in the grace period.",
   "ar": "ابحث في بريدك عن كلمات التجديد وانتهاء الصلاحية واسم نطاقك، فانتهاء النطاق هو أشيع الأسباب ويُصلَح في دقائق إن أدركته في فترة السماح."},
  {"en": "Log in to your hosting account. Suspended for non payment or for exceeding a limit shows on the first screen.",
   "ar": "سجّل الدخول إلى حساب الاستضافة، فالتعليق لعدم الدفع أو لتجاوز حدّ ما يظهر في الشاشة الأولى."},
  {"en": "If you changed anything in the last few days, a plugin, a theme, DNS settings, that change is the prime suspect. Undo it if you can.",
   "ar": "وإن كنت قد غيّرت شيئاً في الأيام الأخيرة، من إضافة أو قالب أو إعدادات DNS، فذلك التغيير هو المتّهم الأول، فتراجع عنه إن استطعت."},
 ],
 "stop": {"en": "If the domain has expired past its grace period, or the site was hacked, time matters. Send us the address and whatever error you see and we will tell you within the hour what it is.",
          "ar": "فإن انتهى النطاق وتجاوز فترة السماح أو اختُرق الموقع فالوقت مهمّ، فأرسل لنا العنوان وأيّ خطأ تراه ونخبرك خلال ساعة بما هو."},
},
{
 "slug": "is-my-website-secure", "category": "websites", "urgency": "normal",
 "title": {"en": "Is my website secure? The five minute check", "ar": "هل موقعي آمن؟ الفحص في خمس دقائق"},
 "summary": {"en": "Five things anyone can check without technical knowledge, and what a fail on each one means.",
             "ar": "خمسة أمور يستطيع أيّ أحد فحصها دون معرفة تقنية، وما يعنيه الإخفاق في كلّ منها."},
 "keywords": {"en": "website security https padlock hacked updates wordpress admin password", "ar": "أمان الموقع قفل اختراق تحديثات كلمة مرور"},
 "steps": [
  {"en": "Look for the padlock. Open your site and check the address bar. No padlock, or a warning, means visitors are being told your site is not safe, and Google marks it down.",
   "ar": "ابحث عن القفل، فافتح موقعك وانظر في شريط العنوان، وغياب القفل أو ظهور تحذير يعني أنّ الزوّار يُبلَّغون بأنّ موقعك غير آمن، وجوجل يخفض ترتيبه."},
  {"en": "Check for updates. If it is WordPress or similar, log in and look for the updates count. A site months behind on updates is the way most small sites get hacked.",
   "ar": "افحص التحديثات، فإن كان ووردبريس أو ما شابهه فسجّل الدخول وانظر إلى عدد التحديثات، فموقع متأخّر شهوراً عن التحديثات هو الطريقة التي تُخترق بها أغلب المواقع الصغيرة."},
  {"en": "Try the login page with the username admin. If it exists, rename it. Automated attacks try admin first, thousands of times a day.",
   "ar": "جرّب صفحة الدخول باسم المستخدم admin، فإن كان موجوداً فغيّره، لأنّ الهجمات الآلية تجرّب admin أولاً آلاف المرّات في اليوم."},
  {"en": "Ask when the last backup was and where it is. If the answer is not sure, you do not have one. A hacked site with a backup is an afternoon; without one it can be a rebuild.",
   "ar": "اسأل متى كانت آخر نسخة احتياطية وأين هي، فإن كان الجواب لست متأكداً فليست لديك نسخة، والموقع المخترَق مع نسخة عمل عصر واحد، ومن دونها قد يكون إعادة بناء."},
  {"en": "Search Google for your domain name and look at the results. Pages you did not create, or listings in another language, mean it has already been compromised.",
   "ar": "ابحث في جوجل عن اسم نطاقك وانظر إلى النتائج، فصفحات لم تنشئها أنت أو نتائج بلغة أخرى تعني أنّه اختُرق بالفعل."},
 ],
 "stop": {"en": "Any fail on the padlock or the Google search needs attention this week, not this quarter. Send us the address and we will do the full check and give you a plain list.",
          "ar": "وأيّ إخفاق في القفل أو في بحث جوجل يحتاج عناية هذا الأسبوع لا هذا الفصل، فأرسل لنا العنوان ونجري الفحص الكامل ونعطيك قائمة واضحة."},
},
{
 "slug": "website-is-slow", "category": "websites", "urgency": "low",
 "title": {"en": "My website is slow", "ar": "موقعي بطيء"},
 "summary": {"en": "Slow sites lose visitors before they see anything. The three usual causes and how to see which is yours.",
             "ar": "المواقع البطيئة تخسر الزوّار قبل أن يروا شيئاً، وهذه الأسباب الثلاثة المعتادة وكيف تعرف أيّها عندك."},
 "keywords": {"en": "website slow loading speed images hosting plugins performance", "ar": "موقع بطيء تحميل سرعة صور استضافة إضافات"},
 "steps": [
  {"en": "Test it the way visitors see it, on a phone on mobile data. That is the real speed. A fast office connection hides everything.",
   "ar": "جرّبه كما يراه الزوّار، على هاتف ببيانات الجوّال، فتلك هي السرعة الحقيقية، واتصال المكتب السريع يخفي كلّ شيء."},
  {"en": "Right click any large image on the site and open it in a new tab. If the image itself is several megabytes, that is your problem. Photos straight from a camera or phone are ten times bigger than a website needs.",
   "ar": "انقر بزرّ الفأرة الأيمن على أيّ صورة كبيرة في الموقع وافتحها في تبويب جديد، فإن كان حجمها عدّة ميجابايت فهذه مشكلتك، والصور المأخوذة مباشرة من الكاميرا أو الهاتف أكبر بعشر مرّات ممّا يحتاجه الموقع."},
  {"en": "Count the plugins if it is WordPress. More than fifteen active plugins, or any you cannot say the purpose of, slow every single page load.",
   "ar": "عدّ الإضافات إن كان ووردبريس، فأكثر من خمس عشرة إضافة نشطة أو أيّ إضافة لا تعرف الغرض منها تُبطئ كلّ تحميل صفحة."},
  {"en": "Check what hosting you are on. The cheapest shared plans put hundreds of sites on one machine. If your site was fast a year ago and nothing changed, the hosting probably got more crowded.",
   "ar": "انظر إلى نوع الاستضافة، فأرخص الخطط المشتركة تضع مئات المواقع على جهاز واحد، وإن كان موقعك سريعاً قبل سنة ولم يتغيّر شيء فالأرجح أنّ الاستضافة ازدحمت."},
  {"en": "Run it through a free speed test online and look at the largest items in the list. That tells you whether it is images, scripts or the server itself.",
   "ar": "شغّله في اختبار سرعة مجاني على الإنترنت وانظر إلى أكبر العناصر في القائمة، فذلك يخبرك هل المشكلة في الصور أم في السكربتات أم في الخادم نفسه."},
 ],
 "stop": {"en": "If images are the cause, that is a one time fix we can do in an afternoon. If it is the hosting, moving a site is routine but needs care with email and DNS. Either way, send us the address.",
          "ar": "فإن كانت الصور هي السبب فذلك إصلاح لمرة واحدة ننجزه في عصر واحد، وإن كانت الاستضافة فنقل الموقع عمل روتيني لكنه يحتاج عناية بالبريد وDNS، وفي الحالتين أرسل لنا العنوان."},
},
{
 "slug": "spotting-a-scam-message", "category": "safety", "urgency": "normal",
 "title": {"en": "Is this message a scam?", "ar": "هل هذه الرسالة احتيال؟"},
 "summary": {"en": "The tells that give away nearly every scam email, text and call, and the one rule that beats all of them.",
             "ar": "العلامات التي تفضح أغلب رسائل الاحتيال والمكالمات، والقاعدة الواحدة التي تغلبها كلّها."},
 "keywords": {"en": "scam phishing fraud suspicious email text call bank otp link", "ar": "احتيال تصيّد رسالة مشبوهة بنك رمز تحقّق رابط"},
 "steps": [
  {"en": "Urgency is the first tell. Your account will be closed today, a parcel is waiting, a fine is due now. Real organisations do not need you to act in the next ten minutes.",
   "ar": "الاستعجال هو العلامة الأولى، فحسابك سيُغلق اليوم أو طرد ينتظرك أو غرامة مستحقّة الآن، والجهات الحقيقية لا تحتاج منك أن تتصرّف في الدقائق العشر القادمة."},
  {"en": "Look at the sender, not the name. Tap or hover on it to see the actual address. A bank does not write from a free email service or from a domain with extra words in it.",
   "ar": "انظر إلى المرسِل لا إلى الاسم، فاضغط عليه أو مرّر فوقه لترى العنوان الفعلي، والبنك لا يراسل من خدمة بريد مجانية ولا من نطاق فيه كلمات زائدة."},
  {"en": "Do not tap the link. If it claims to be your bank or a service you use, close the message and open the real app or type the address yourself. If it is real, it will be there too.",
   "ar": "لا تضغط الرابط، فإن زعمت أنّها من بنكك أو من خدمة تستعملها فأغلق الرسالة وافتح التطبيق الحقيقي أو اكتب العنوان بنفسك، فإن كان الأمر حقيقياً فستجده هناك أيضاً."},
  {"en": "Nobody legitimate ever asks for a one time code, a PIN or a full card number over the phone or in a message. Not the bank, not the police, not the telecom company. That request alone is the answer.",
   "ar": "لا أحد شرعيّ يطلب رمز تحقّق لمرة واحدة أو رقماً سرّياً أو رقم بطاقة كاملاً عبر الهاتف أو في رسالة، لا البنك ولا الشرطة ولا شركة الاتصالات، وذلك الطلب وحده هو الجواب."},
  {"en": "If you already tapped or replied, do not panic and do not delete anything. Change the password on that account from a different device, and call your bank on the number printed on your card.",
   "ar": "وإن كنت قد ضغطت أو رددت فلا تفزع ولا تحذف شيئاً، وغيّر كلمة مرور ذلك الحساب من جهاز آخر، واتصل ببنكك على الرقم المطبوع على بطاقتك."},
 ],
 "stop": {"en": "If money has moved or you have shared a code, the first hour matters most. Call the bank first, then get in touch with us and we will help you work out what else needs securing.",
          "ar": "فإن كان مال قد تحرّك أو شاركت رمزاً فالساعة الأولى هي الأهمّ، فاتصل بالبنك أولاً ثم تواصل معنا ونساعدك على معرفة ما ينبغي تأمينه غير ذلك."},
},
]
