#!/usr/bin/env python3
"""
help.eworldq8.com preflight.

This is a consumer page. Somebody will act on what it says, so the gates are
mostly about not telling them something untrue: no invented prices, no
invented phone number, no promise the business has not made, and no triage
path that dead ends.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEXT = {".html", ".css", ".js", ".md", ".txt", ".xml", ".json", ".yml", ".yaml", ".svg"}
SKIP = {".git", "node_modules"}
DASHES = {"\u2012": "U+2012", "\u2013": "U+2013", "\u2014": "U+2014", "\u2015": "U+2015"}
failures, notices = [], []

html = lambda: (ROOT / "index.html").read_text(encoding="utf-8")
data = lambda: (ROOT / "assets" / "data.js").read_text(encoding="utf-8")


def files():
    for p in sorted(ROOT.rglob("*")):
        if p.is_file() and p.suffix.lower() in TEXT and not any(s in p.parts for s in SKIP):
            yield p


def gate_unicode_dashes():
    hits = 0
    for p in files():
        try: lines = p.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError: continue
        for n, line in enumerate(lines, 1):
            for ch, label in DASHES.items():
                if ch in line:
                    failures.append(f"{p.relative_to(ROOT)}:{n} contains {label}")
                    hits += 1
    return hits == 0


def gate_attribution():
    hits = 0
    for p in files():
        try: t = p.read_text(encoding="utf-8").lower()
        except UnicodeDecodeError: continue
        for m in ("claude.ai", "anthropic", "generated by claude"):
            if m in t:
                failures.append(f"{p.relative_to(ROOT)} contains attribution marker: {m}")
                hits += 1
    return hits == 0


def gate_no_custom_domain_yet():
    """
    help.eworldq8.com has no DNS record. Binding it now would make GitHub
    redirect the working github.io address to one that does not resolve,
    which is exactly how a live site disappears.
    """
    if (ROOT / "CNAME").exists():
        failures.append("CNAME is present, but help.eworldq8.com has no DNS record yet")
        return False
    line = [l for l in html().splitlines() if 'rel="canonical"' in l]
    if line and "siteq8.github.io/help-eworldq8" not in line[0]:
        failures.append("the canonical points somewhere the site is not served from")
        return False
    return True


def gate_nojekyll():
    if not (ROOT / ".nojekyll").exists():
        failures.append(".nojekyll is missing")
        return False
    return True


def gate_no_invented_details():
    """
    A price or a phone number that nobody agreed to is worse than a blank.
    Unset is fine, a placeholder is not.
    """
    d, h = data(), html()
    ok = True
    for bad in ("TODO", "REPLACE", "xxx-xxx", "123 456", "+965 0000", "lorem", "example.com"):
        for src, name in ((d, "data.js"), (h, "index.html")):
            if bad.lower() in src.lower():
                failures.append(f"placeholder left in {name}: {bad}")
                ok = False
    # currency figures anywhere on a page with no agreed price list
    money = re.findall(r"\b(?:KD|KWD|\$)\s?\d", h) + re.findall(r"\b(?:KD|KWD|\$)\s?\d", d)
    if money:
        failures.append(f"a price appears on the page but no price list was agreed: {money[:3]}")
        ok = False
    unset = [k for k in ("phone", "whatsapp", "hours", "address")
             if re.search(rf"{k}:\s*null", d)]
    if unset:
        notices.append("ACTION NEEDED: " + ", ".join(unset) + " are unset, so they do not render. "
                       "Fill them in assets/data.js and each appears on its own.")
    return ok


def gate_promises_are_kept():
    """
    The page makes two commitments in the hero and the steps. If the wording
    is edited to promise something bigger, that is a business decision, not a
    copy tweak, so it has to fail the build and be looked at.
    """
    h = html().lower()
    ok = True
    for over in ("guaranteed", "same day", "24/7", "instant", "any problem", "we can fix anything",
                 "no fix no fee", "lifetime warranty"):
        if over in h:
            failures.append(f"the page promises something nobody agreed to: '{over}'")
            ok = False
    return ok


def gate_triage_is_complete():
    """Every path a visitor can click has to land on an answer."""
    src = data()
    ok = True
    sym_block = src.split('"symptoms":')[1].split('"answers":')[0]
    devices = re.findall(r'"(\w+)":\s*\[', sym_block)
    ans = set(re.findall(r'"(\w+:\w+)":\s*\{', src.split('"answers":')[1]))
    paths = 0
    for dev in devices:
        chunk = re.search(rf'"{dev}":\s*\[(.*?)\n    \]', sym_block, re.S)
        if not chunk:
            failures.append(f"device '{dev}' has no symptom list")
            ok = False
            continue
        for sym in re.findall(r'"key":\s*"(\w+)"', chunk.group(1)):
            paths += 1
            if f"{dev}:{sym}" not in ans:
                failures.append(f"triage path with no answer: {dev}:{sym}")
                ok = False
    if paths == 0:
        failures.append("the triage has no paths at all")
        ok = False
    print(f"    triage: {len(devices)} devices, {paths} paths, {len(ans)} answers")
    return ok


def gate_triage_does_not_diagnose():
    """
    A page cannot see the machine. Telling somebody their drive has failed
    when it has not sends them to buy a drive they do not need.
    """
    src = data() + (ROOT / "assets" / "app.js").read_text(encoding="utf-8")
    ok = True
    if "not a diagnosis" not in src:
        failures.append("the result never says it is not a diagnosis")
        ok = False
    for claim in ("your drive has failed", "you need a new", "it is definitely", "this is certainly"):
        if claim in src.lower():
            failures.append(f"the triage states a certainty it cannot have: '{claim}'")
            ok = False
    return ok


def gate_bilingual_coverage():
    """
    Every visible string has to exist in both languages. A half translated
    page is worse than an English one, because the visitor cannot tell which
    parts they are missing.
    """
    import json as _json
    src = data()
    ok = True
    # every en needs an ar beside it
    pairs = len(re.findall(r'"en":\s*"', src))
    ars = len(re.findall(r'"ar":\s*"', src))
    if pairs != ars:
        failures.append(f"bilingual mismatch: {pairs} english strings, {ars} arabic")
        ok = False
    empty = re.findall(r'"ar":\s*""', src)
    if empty:
        failures.append(f"{len(empty)} arabic strings are empty")
        ok = False
    # and every data-t key in the markup has to exist in UI
    keys = set(re.findall(r'data-t="(\w+)"', html()))
    have = set(re.findall(r'"(\w+)":\s*\{\s*"en"', src))
    missing = sorted(keys - have)
    if missing:
        failures.append("markup asks for strings that do not exist: " + ", ".join(missing))
        ok = False
    print(f"    bilingual: {pairs} string pairs, {len(keys)} markup keys")
    return ok


def gate_western_digits():
    """
    Arabic copy here uses Western digits, which is what Kuwait uses in
    practice. A mix of both on one page looks like a mistake.
    """
    bad = re.findall(r"[\u0660-\u0669\u06F0-\u06F9]", data() + html())
    if bad:
        failures.append(f"{len(bad)} Arabic-Indic digits found; this site uses Western digits")
        return False
    return True


def gate_rtl_is_real():
    """
    Setting dir without logical properties gives a page that is mirrored in
    direction but still padded on the wrong side.
    """
    css = (ROOT / "assets" / "styles.css").read_text(encoding="utf-8")
    js = (ROOT / "assets" / "site.js").read_text(encoding="utf-8")
    ok = True
    if 'root.dir = lang === "ar" ? "rtl" : "ltr"' not in js:
        failures.append("the document direction is never switched for Arabic")
        ok = False
    physical = re.findall(r"\n\s*(padding-left|padding-right|margin-left|margin-right|left|right):", css)
    if len(physical) > 2:
        failures.append(f"{len(physical)} physical side properties in the stylesheet; RTL will not follow")
        ok = False
    return ok


def gate_guides_are_substantial():
    """
    The guides are the point of a help site. Each has to be followable on
    its own: a real title, a summary, at least four steps in both languages,
    and a stop line saying when to ask, because the wrong step at the wrong
    moment does more harm than the original problem.
    """
    import sys as _sys
    _sys.path.insert(0, str(ROOT / "content"))
    import importlib, guides as G
    importlib.reload(G)
    ok = True
    slugs = set()
    for g in G.GUIDES:
        for field in ("title", "summary", "stop", "keywords"):
            v = g.get(field, {})
            if not (v.get("en") and v.get("ar")):
                failures.append(f"guide {g.get('slug')}: {field} is missing a language")
                ok = False
        if len(g.get("steps", [])) < 4:
            failures.append(f"guide {g['slug']}: fewer than four steps")
            ok = False
        for i, st in enumerate(g.get("steps", [])):
            if not (st.get("en") and st.get("ar")):
                failures.append(f"guide {g['slug']}: step {i+1} is missing a language")
                ok = False
        if g["slug"] in slugs:
            failures.append(f"duplicate slug {g['slug']}")
            ok = False
        slugs.add(g["slug"])
        if g["category"] not in {c["key"] for c in G.CATEGORIES}:
            failures.append(f"guide {g['slug']}: unknown category {g['category']}")
            ok = False
    print(f"    guides: {len(G.GUIDES)} in {len(G.CATEGORIES)} categories")
    return ok


def gate_generated_pages_are_current():
    """
    The guide pages are committed output. If content changes and the build
    was not rerun, the site serves the old guide. Regenerate to a scratch
    copy and compare.
    """
    import subprocess, tempfile, shutil, filecmp
    ok = True
    with tempfile.TemporaryDirectory() as tmp:
        scratch = pathlib.Path(tmp) / "site"
        shutil.copytree(ROOT, scratch, ignore=shutil.ignore_patterns(".git", "node_modules"))
        subprocess.run([sys.executable, str(scratch / "tools" / "build.py")],
                       capture_output=True, text=True, check=True)
        for rel in ["guides/index.html", "search.json"] + \
                   [f"guides/{d.name}/index.html" for d in (scratch / "guides").iterdir() if d.is_dir()]:
            a, b = ROOT / rel, scratch / rel
            if not a.exists():
                failures.append(f"generated page missing: {rel}, run tools/build.py")
                ok = False
            elif not filecmp.cmp(a, b, shallow=False):
                failures.append(f"generated page is stale: {rel}, run tools/build.py")
                ok = False
    return ok


def gate_internal_links_resolve():
    """A help site with a dead link inside it has failed at the one job."""
    ok = True
    pages = [ROOT / "index.html", ROOT / "guides" / "index.html"] + \
            [p for p in (ROOT / "guides").glob("*/index.html")]
    for page in pages:
        base = page.parent
        for href in re.findall(r'href="([^"#?]+)', page.read_text(encoding="utf-8")):
            if href.startswith(("http", "mailto:", "tel:")):
                continue
            target = (base / href).resolve()
            if target.is_dir():
                target = target / "index.html"
            if not target.exists():
                failures.append(f"{page.relative_to(ROOT)} links to {href}, which does not exist")
                ok = False
    return ok


GATES = [
    ("unicode dashes", gate_unicode_dashes),
    ("attribution", gate_attribution),
    ("no custom domain yet", gate_no_custom_domain_yet),
    (".nojekyll", gate_nojekyll),
    ("no invented details", gate_no_invented_details),
    ("promises are kept", gate_promises_are_kept),
    ("bilingual coverage", gate_bilingual_coverage),
    ("western digits", gate_western_digits),
    ("rtl is real", gate_rtl_is_real),
    ("triage is complete", gate_triage_is_complete),
    ("triage does not diagnose", gate_triage_does_not_diagnose),
    ("guides are substantial", gate_guides_are_substantial),
    ("generated pages are current", gate_generated_pages_are_current),
    ("internal links resolve", gate_internal_links_resolve),
]


def main():
    print("preflight :: help.eworldq8.com")
    passed = 0
    for name, fn in GATES:
        before = len(failures)
        ok = fn()
        good = ok and len(failures) == before
        print(f"  [{'pass' if good else 'FAIL'}] {name}")
        passed += good
    if notices:
        print()
        for n in notices: print(f"  {n}")
    if failures:
        print(f"\n{len(failures)} problem(s):")
        for f in failures: print(f"  {f}")
        print(f"\n{passed}/{len(GATES)} gates passed. Not ready to publish.")
        return 1
    print(f"\n{passed}/{len(GATES)} gates passed. Ready to publish.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
