#!/usr/bin/env python3
"""
help.eworldq8.com preflight.

This is a consumer page. Somebody will act on what it says, so the gates are
mostly about not telling them something untrue: no invented prices, no
invented phone number, no promise the business has not made, and no triage
path that dead ends.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEXT = {".html", ".css", ".js", ".md", ".txt", ".xml", ".json", ".yml", ".yaml", ".svg"}
SKIP = {".git", "node_modules"}
DASHES = {"\u2012": "U+2012", "\u2013": "U+2013", "\u2014": "U+2014", "\u2015": "U+2015"}
failures, notices = [], []

html = lambda: (ROOT / "index.html").read_text(encoding="utf-8")
data = lambda: (ROOT / "assets" / "data.js").read_text(encoding="utf-8")


def files():
    for p in sorted(ROOT.rglob("*")):
        if p.is_file() and p.suffix.lower() in TEXT and not any(s in p.parts for s in SKIP):
            yield p


def gate_unicode_dashes():
    hits = 0
    for p in files():
        try: lines = p.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError: continue
        for n, line in enumerate(lines, 1):
            for ch, label in DASHES.items():
                if ch in line:
                    failures.append(f"{p.relative_to(ROOT)}:{n} contains {label}")
                    hits += 1
    return hits == 0


def gate_attribution():
    hits = 0
    for p in files():
        try: t = p.read_text(encoding="utf-8").lower()
        except UnicodeDecodeError: continue
        for m in ("claude.ai", "anthropic", "generated by claude"):
            if m in t:
                failures.append(f"{p.relative_to(ROOT)} contains attribution marker: {m}")
                hits += 1
    return hits == 0


def gate_no_custom_domain_yet():
    """
    help.eworldq8.com has no DNS record. Binding it now would make GitHub
    redirect the working github.io address to one that does not resolve,
    which is exactly how a live site disappears.
    """
    if (ROOT / "CNAME").exists():
        failures.append("CNAME is present, but help.eworldq8.com has no DNS record yet")
        return False
    line = [l for l in html().splitlines() if 'rel="canonical"' in l]
    if line and "siteq8.github.io/help-eworldq8" not in line[0]:
        failures.append("the canonical points somewhere the site is not served from")
        return False
    return True


def gate_nojekyll():
    if not (ROOT / ".nojekyll").exists():
        failures.append(".nojekyll is missing")
        return False
    return True


def gate_no_invented_details():
    """
    A price or a phone number that nobody agreed to is worse than a blank.
    Unset is fine, a placeholder is not.
    """
    d, h = data(), html()
    ok = True
    for bad in ("TODO", "REPLACE", "xxx-xxx", "123 456", "+965 0000", "lorem", "example.com"):
        for src, name in ((d, "data.js"), (h, "index.html")):
            if bad.lower() in src.lower():
                failures.append(f"placeholder left in {name}: {bad}")
                ok = False
    # currency figures anywhere on a page with no agreed price list
    money = re.findall(r"\b(?:KD|KWD|\$)\s?\d", h) + re.findall(r"\b(?:KD|KWD|\$)\s?\d", d)
    if money:
        failures.append(f"a price appears on the page but no price list was agreed: {money[:3]}")
        ok = False
    unset = [k for k in ("phone", "whatsapp", "hours", "address")
             if re.search(rf"{k}:\s*null", d)]
    if unset:
        notices.append("ACTION NEEDED: " + ", ".join(unset) + " are unset, so they do not render. "
                       "Fill them in assets/data.js and each appears on its own.")
    return ok


def gate_promises_are_kept():
    """
    The page makes two commitments in the hero and the steps. If the wording
    is edited to promise something bigger, that is a business decision, not a
    copy tweak, so it has to fail the build and be looked at.
    """
    h = html().lower()
    ok = True
    for over in ("guaranteed", "same day", "24/7", "instant", "any problem", "we can fix anything",
                 "no fix no fee", "lifetime warranty"):
        if over in h:
            failures.append(f"the page promises something nobody agreed to: '{over}'")
            ok = False
    return ok


def gate_triage_is_complete():
    """Every path a visitor can click has to land on an answer."""
    src = data()
    devices = re.findall(r'\{ key: "(\w+)",\s+label:', src.split("symptoms:")[0])
    ok = True
    sym_block = src.split("symptoms: {")[1].split("answers:")[0]
    ans = set(re.findall(r'"(\w+:\w+)":', src.split("answers:")[1]))
    paths = 0
    for dev in devices:
        chunk = re.search(rf"{dev}:\s*\[(.*?)\]", sym_block, re.S)
        if not chunk:
            failures.append(f"device '{dev}' has no symptom list")
            ok = False
            continue
        for sym in re.findall(r'\{ key: "(\w+)"', chunk.group(1)):
            paths += 1
            if f"{dev}:{sym}" not in ans:
                failures.append(f"triage path with no answer: {dev}:{sym}")
                ok = False
    if paths == 0:
        failures.append("the triage has no paths at all")
        ok = False
    print(f"    triage: {len(devices)} devices, {paths} paths, {len(ans)} answers")
    return ok


def gate_triage_does_not_diagnose():
    """
    A page cannot see the machine. Telling somebody their drive has failed
    when it has not sends them to buy a drive they do not need.
    """
    src = data() + (ROOT / "assets" / "app.js").read_text(encoding="utf-8")
    ok = True
    if "not a diagnosis" not in src:
        failures.append("the result never says it is not a diagnosis")
        ok = False
    for claim in ("your drive has failed", "you need a new", "it is definitely", "this is certainly"):
        if claim in src.lower():
            failures.append(f"the triage states a certainty it cannot have: '{claim}'")
            ok = False
    return ok


GATES = [
    ("unicode dashes", gate_unicode_dashes),
    ("attribution", gate_attribution),
    ("no custom domain yet", gate_no_custom_domain_yet),
    (".nojekyll", gate_nojekyll),
    ("no invented details", gate_no_invented_details),
    ("promises are kept", gate_promises_are_kept),
    ("triage is complete", gate_triage_is_complete),
    ("triage does not diagnose", gate_triage_does_not_diagnose),
]


def main():
    print("preflight :: help.eworldq8.com")
    passed = 0
    for name, fn in GATES:
        before = len(failures)
        ok = fn()
        good = ok and len(failures) == before
        print(f"  [{'pass' if good else 'FAIL'}] {name}")
        passed += good
    if notices:
        print()
        for n in notices: print(f"  {n}")
    if failures:
        print(f"\n{len(failures)} problem(s):")
        for f in failures: print(f"  {f}")
        print(f"\n{passed}/{len(GATES)} gates passed. Not ready to publish.")
        return 1
    print(f"\n{passed}/{len(GATES)} gates passed. Ready to publish.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
